### PR TITLE
get rid of this switch statement in playstate that doesnt contain any cases

### PR DESCRIPTION
**Pull request by arthu-rguo**
the most important pr ever...

### CODE REVIEW

**Comment by isakube** [comment]
i mean i got rid of it in my mod but if you want something special to happen when playing from freeplay that's kinda a thingy

**Comment by Spel0** [comment]
Best PR, can't live without it, thanks dog man! ❤️

**Review by Spel0 — APPROVED** [review]

**Review by ACardboardBox1 — APPROVED** [review]
thank

**Review by trayfellow — APPROVED** [review]
yes.

**Review by SimplyMerlin — APPROVED** [review]

**Review by isakube — APPROVED** [review]
:(

**Review by Jaduplex — APPROVED** [review]
greatest pr ever made, life changing

**Review by CrystalSlime — APPROVED** [review]

**Pull request merged**
