### PR TITLE
cleaned codebase, game runs much faster now

### PR DESCRIPTION
**Pull request by AlekEagle**

### CODE REVIEW

**Comment by Kade-github** [comment]
thank you github workflow for saying all of the checks passed. Great service 10/10. Thanks for the commit. merged!

**Review by danii — APPROVED** [review]
i agree

**Review by AlekEagle — COMMENTED** [review]
i approve these changes, they are very cool and make game very fun

**Comment by Jaduplex** [comment]
haha you are so funniest you make funny pr that do kooky thing haha!!! please laugh

**Comment by actuallyasmartname** [comment]
so good

**Pull request closed without merging**
