### PR TITLE
no

### PR DESCRIPTION
**Pull request by RagdollClash**
no

### CODE REVIEW

**Comment by Jaduplex** [comment]
~~good idea. only change i'd make is also have it copy over the art folder~~ after @daniel11420 has explained why this is a bad idea, i am retracting this statement

**Comment by RagdollClash** [comment]
not a good idea as it'll heavily increase the download size due to the flash files

**Comment by puyoxyz** [comment]
This is literally the stupidest PR I have ever seen.

**Comment by Jaduplex** [comment]
> This is literally the stupidest PR I have ever seen.

you didn't have to be rude about it. the fuck is your problem?

**Comment by puyoxyz** [comment]
> > This is literally the stupidest PR I have ever seen.
> 
> you didn't have to be rude about it. the fuck is your problem?

It's??? Including??? The source code??? In builds??? Source code is supposed to be distributed separately??? And it increases file size a bunch??? 

(And even if we did something like this there should be an option to disable it, for, like, for example, *our own CI builds to not take years to download*?)

**Comment by Jaduplex** [comment]
> > > This is literally the stupidest PR I have ever seen.
> > 
> > 
> > you didn't have to be rude about it. the fuck is your problem?
> 
> It's??? Including??? The source code??? In builds??? Source code is supposed to be distributed separately??? And it increases file size a bunch???

yeah but the way you said it is needlessly rude. you coulda just explained why it was a bad idea

**Comment by puyoxyz** [comment]
> > > > This is literally the stupidest PR I have ever seen.
> > > 
> > > 
> > > you didn't have to be rude about it. the fuck is your problem?
> > 
> > 
> > It's??? Including??? The source code??? In builds??? Source code is supposed to be distributed separately??? And it increases file size a bunch???
> 
> yeah but the way you said it is needlessly rude. you coulda just explained why it was a bad idea

Okay Sorry you are Right;;;; i was mad bc someone else was being needlessly rude to me in another pr (but not me specifically? but to whoever wrote the readme? but i guess that counts as me?) but yeah ur right that doesn't mean I can be needlessly rude to people I guess yeah

**Comment by Jaduplex** [comment]
> > > > > This is literally the stupidest PR I have ever seen.
> > > > 
> > > > 
> > > > you didn't have to be rude about it. the fuck is your problem?
> > > 
> > > 
> > > It's??? Including??? The source code??? In builds??? Source code is supposed to be distributed separately??? And it increases file size a bunch???
> > 
> > 
> > yeah but the way you said it is needlessly rude. you coulda just explained why it was a bad idea
> 
> Okay Sorry you are Right;;;; i was mad bc someone else was being needlessly rude to me in another pr (but not me specifically? but to whoever wrote the readme? but i guess that counts as me?) but yeah ur right that doesn't mean I can be needlessly rude to people I guess yeah

i was rude in that reply myself. its alright. although i have a feeling the other rude pr's name might have been a joke, i understand

**Comment by puyoxyz** [comment]
image
copying this here too i guess

**Comment by RagdollClash** [comment]
stop

**Comment by Kade-github** [comment]
the author has already stated that he doesn't want this. lets just move on?

**Pull request closed without merging**
