### PR TITLE
add skip cutscene options

### PR DESCRIPTION
**Pull request by napstaa967**
this is for issue #1445

### CODE REVIEW

**Comment by ACardboardBox1** [comment]
feel like this should be combined into one option rather than two

**Comment by ACardboardBox1** [comment]
also im pretty sure (dont know for sure) but if you do a cutscene like the one in thorns, it wont show in freeplay. so yeah, i feel like this needs a bit more work 
also merging into **stable** 
(keep in mind that i am omega dumbass so i might not always be correct)

**Comment by napstaa967** [comment]
> feel like this should be combined into one option rather than two

i actually wanted to do this but my trash skills on coding weren't good enough to make it one setting so i split it on 2 for now

**Comment by napstaa967** [comment]
> also im pretty sure (dont know for sure) but if you do a cutscene like the one in thorns, it wont show in freeplay. so yeah, i feel > like this needs a bit more work
> also merging into stable
> (keep in mind that i am omega dumbass so i might not always be correct)

the thorns anim does play as its part of schoolintro which is inside the if statement that checks for the setting being set to not skip

im merging into stable because that's the only branch i have downloaded and already compiled, i don't like waiting for hours to build the game again

**Comment by napstaa967** [comment]
have to make a new pull, closing this one

**Pull request closed without merging**
