### PR TITLE
d

### PR DESCRIPTION
**Pull request by Xela10001**

### CODE REVIEW

**Comment by Xela10001** [comment]
In this example, these sentences not only have different positions, but they are also 0.5 times the size of normal text

image

**Comment by isakube** [comment]
I've never met an over-commenter before. Pleased to meet you /hj

**Comment by Xela10001** [comment]
**Copy and pasted from the commit**
Added a function called resizeText, which can be used on already existing text to make it bigger or smaller, and even has a boolean incase you want the text to keep its midpoint or not.
**Copy and pasted from the commit**

Here is a recording of it in action. I have this menu where the text, which was only created once i entered the StoryMenuState,
is using the function to be able to become bigger and smaller.
Its not extremely noticeable, as its being increased and decreased from 0.5 scale to 0.6, but it is working, and should work for any other scales.

https://user-images.githubusercontent.com/47480171/128571645-307cdd35-1ebe-4a77-9555-b4bd7b102389.mp4

**Review by isakube — APPROVED** [review]
> yee yee, i'm vibin with it

\- HD Boyfriend

**Pull request merged**
