### PR TITLE
difficulty selector in charting state

### PR DESCRIPTION
**Pull request by RagdollClash**
https://user-images.githubusercontent.com/15317421/116766622-4af0de00-a9e0-11eb-8602-ad3d639a7cef.mp4

### CODE REVIEW

**Comment by RagdollClash** [comment]
never in my life would i have thought i would ever get frustrated at tabs

**Comment by isakube** [comment]
yooo pog, if i could approve i would

**Review by theDetourist — APPROVED** [review]
Rad.

**Review by haya3218 — APPROVED** [review]
Atleast it ain't sarv engine™.

Besides that, nice job!

**Comment by Kade-github** [comment]
this already exists :(

**Comment by RagdollClash** [comment]
wait wtf where is it

**Comment by haya3218** [comment]
yeah where is it kademan

**Pull request closed without merging**
