### PR TITLE
New charting menu feature: song time and section shifting

### PR DESCRIPTION
**Pull request by Spel0**
Showcase:

https://user-images.githubusercontent.com/75626813/128491360-194186c7-33e6-470b-ab4e-04e02be1de4e.mp4

**This PR also fixes notes shifting crash and json reloading crash on songs like dad battle and philly nice**

### CODE REVIEW

**Review by isakube — CHANGES_REQUESTED** [review]
`var stepperSniftToTime =  new FlxUINumericStepper(225, 165, 1, 0, 0, FlxG.sound.music.length / 1000 - 0.01, 2);`

"""fixed"""

**Comment by Spel0** [comment]
> """fixed"""

Fixed what?

**Comment by isakube** [comment]
> > """fixed"""
> 
> Fixed what?

the stepper had an interval of 5 seconds so i changed it to be more precise

**Comment by Spel0** [comment]
> the stepper had an interval of 5 seconds so i changed it to be more precise

That's the whole point of this PR, to navigate through huge chunk of chart easily... Why would you need a button to go 1 seconds further if you can just scroll down???

**Review by isakube — APPROVED** [review]
boop

**Comment by Kade-github** [comment]
I did you one better https://github.com/KadeDev/Kade-Engine/commit/bc623721b1c1d5cd53e2b3370df571da9be41af9

**Pull request closed without merging**
