### PR TITLE
Opponents strumline also glow on notes hit

### PR DESCRIPTION
**Pull request by theDetourist**
It's open source now, eh? Besides, it should have been implemented already.

yo

### CODE REVIEW

**Comment by NeeEoo** [comment]
I'm not sure but the code looks a lot similar to the code from pull request 292. But was later reverted when it was found out that the code was stolen from project fnf.

The only difference I can see from that code and this, is that `strumming2` was renamed to `opponentKeyStatus`.

But I could be wrong.

**Comment by theDetourist** [comment]
> 
> 
> I'm not sure but the code looks a lot similar to the code from pull request 292. But was later reverted when it was found out that the code was stolen from project fnf.
> 
> The only difference I can see from that code and this, is that `strumming2` was renamed to `opponentKeyStatus`.
> 
> But I could be wrong.

Same code indeed, but [ProjectFNF is open source **AND** a public repository ](https://github.com/aflacc/ProjectFNF) so it's fair game.

**Comment by puyoxyz** [comment]
ProjectFNF didn't fill out the `Copyright [yyyy] [name of copyright owner]` at the bottom of the Apache license (line 189) and to apply the license you need to fill that out. Because of that, the ProjectFNF code is all rights reserved (since the license does not apply).

So, *if* this code is the code from ProjectFNF, unless you get *explicit permission from the people who made ProjectFNF*, (OR they fix their license and you resubmit the PR after it is fixed) we cannot accept this PR.

> To apply the Apache License to your work, attach the following
boilerplate notice, with the fields enclosed by brackets "[]"
replaced with your own identifying information. (Don't include 
the brackets!)

After looking at the code, it is possible that it's from ProjectFNF, and it's possible that it's not. I'm not sure.

If it's not, changes are approved. If it *is* from ProjectFNF, this PR will be closed.

**Comment by theDetourist** [comment]
Then we're at an impasse, but I don't really care enough to make changes or anything like that since this license thing is quite dense and still not fully solved yet.

The person on Discord who wanted the code for it already got it anyway.

**Pull request closed without merging**
