### PR TITLE
touched up my week guide

### PR DESCRIPTION
**Pull request by isakube**
it's not awful anymore somehow

### CODE REVIEW

**Comment by puyoxyz** [comment]
deploy github pages on that branch and send link so we can see what it looks like pls thanks

**Comment by puyoxyz** [comment]
oh nevermind u did lol im stupid; fix codeblock formatting pls

**Comment by isakube** [comment]
> fix codeblock formatting pls

if you mean [this](https://user-images.githubusercontent.com/68293280/118176567-6d262b00-b3e6-11eb-964f-adfb861de1b3.png), I don't think that's fixable. If you don't then I don't know what you mean

**Comment by puyoxyz** [comment]
> > fix codeblock formatting pls
> 
> if you mean [this](https://user-images.githubusercontent.com/68293280/118176567-6d262b00-b3e6-11eb-964f-adfb861de1b3.png), I don't think that's fixable. If you don't then I don't know what you mean

oh wow that's so wacky i just fixed it (8546dcb)

**Pull request merged**
