### PR TITLE
Make da title screen bump in sync

### PR DESCRIPTION
**Pull request by SimplyMerlin**
Title screen no bump in sync, cause it loops before the next beat hits
this thingy fixes that by just disabling it to loop, and finishing the animation right before it bumps again so it bumps every beat.

pogers

### CODE REVIEW

**Review by Jaduplex — APPROVED** [review]
THANK YOU

**Comment by RagdollClash** [comment]
this was already fixed in #1194

**Comment by ACardboardBox1** [comment]
> 
> 
> this was already fixed in #1194

i had a feeling this was done already

**Comment by SimplyMerlin** [comment]
oh fuck, my bad, forked stable

**Pull request closed without merging**
