### PR TITLE
Skip cutscenes option

### PR DESCRIPTION
**Pull request by c5took**
I saw some dude do this and never got merged so I did it myself

### CODE REVIEW

**Comment by napstaa967** [comment]
i don't know why mine hasn't been merged, kade prob has reasons

**Comment by napstaa967** [comment]
also instead of just making a new pr you can submit changes to stuff

**Review by napstaa967 — APPROVED** [review]

**Comment by c5took** [comment]
> also instead of just making a new pr you can submit changes to stuff

yeah i just wanted to code something

**Comment by c5isnotavailable** [comment]
*code

**Comment by Kade-github** [comment]
I don't like how this is implemented, I'd rather have some sort of button to press in a cutscene instead of an option.

**Pull request closed without merging**
