### PR TITLE
change "dad" variable to "p2"

### PR DESCRIPTION
**Pull request by ajredden**
Also, for consistency, changes all double-quoted strings to single-quoted and adds spaces after all the commas because I hate this code base and myself

### CODE REVIEW

**Review by napstaa967 — APPROVED** [review]

**Comment by napstaa967** [comment]
it is a good idea but some mods will have to change some stuff to work as this changes a lot of stuff

**Review by Spel0 — COMMENTED** [review]
IMO changing dad to P2 is not needed at all. First, it would be confusing as opponent was always referred as 'dad', and not 'P2' everywhere in the code. Second, it breaks dialogues if you want to merge old kade to latest one, unless custom named dialogue portraits were implemented. Third, if you're changing 'dad' to 'P2', then why you didn't change 'boyfriend' to 'P1'? Same consequences as above, but at least it would be consistent and not 50/50 ferris wheel.

**Comment by Futuremappermydud** [comment]
If bf is renamed to p1 then I approve

**Comment by ajredden** [comment]
Then I'd better get to coding

**Comment by ACardboardBox1** [comment]
> 
> 
> IMO changing dad to P2 is not needed at all. First, it would be confusing as opponent was always referred as 'dad', and not 'P2' everywhere in the code. Second, it breaks dialogues if you want to merge old kade to latest one, unless custom named dialogue portraits were implemented. Third, if you're changing 'dad' to 'P2', then why you didn't change 'boyfriend' to 'P1'? Same consequences as above, but at least it would be consistent and not 50/50 ferris wheel.

^

**Comment by ajredden** [comment]
idk what the issue is with maximum sizes being exceeded on appveyor but I don't think it's on my end and everything else seems good

**Comment by napstaa967** [comment]
> idk what the issue is with maximum sizes being exceeded on appveyor but I don't think it's on my end and everything else seems good

its a common thing that shows up for everyone

**Comment by ghost** [comment]
I suggest instead of writing `p1` or `p2`, it would be `enemy` and `player` instead, to avoid further confusion.

**Comment by Spel0** [comment]
Can you comment out HXCPP-debugger btw? Unless we want to force people to use it(which they won't cause smooth brainers), I don't think it's a good idea

**Comment by ACardboardBox1** [comment]
the conflicts 😭

**Comment by ajredden** [comment]
Conflict-free and ready to merge, unless the reviewers believe it can be improved further

**Comment by Hythrex** [comment]
why tho

**Comment by ajredden** [comment]
somehow I fucked up both my remote and local repos so I'm gonna close this pull request and start again, right from the initial fork. I've learned a lot about how git works in a month so my next pr might actually conform to good practice for once

**Pull request closed without merging**
