### PR TITLE
Some fun features

### PR DESCRIPTION
**Pull request by brightfyregit**
This has some little things that spruce up the game, such as arrows lighting up on player 2s side, screenshake when trying to start a locked week, something that updates the health icons in charting state to whatever character you have selected, health bar colors that match the icons, freeplay scroll lag being removed, and the freeplay background changing colors to whatever songs you have selected, just like in the week 7 build -some features are from project fnf

### CODE REVIEW

**Comment by Travdev24** [comment]
oo fancy :D

**Comment by aflacc** [comment]
YOU DIDNT EVEN SAY ITS FROM PROJECT FNF

**Comment by aflacc** [comment]
ALL OF THAT IS FROM PROJECTFNF DUDE

**Comment by brightfyregit** [comment]
> ALL OF THAT IS FROM PROJECTFNF DUDE

i suddenly have a strong urge to credit project fnf

**Comment by aflacc** [comment]
kade pls remove all this stuff Its all my creations and he steal >:l

**Comment by brightfyregit** [comment]
> ALL OF THAT IS FROM PROJECTFNF DUDE

its not all from project fnf lol. charting state updates, removing freeplay lag, and freeplay background changes are things that I made

**Comment by UniversePM** [comment]
image
bruh

**Comment by Kade-github** [comment]
this is literally stealing @brightfyregit. wtf man ur better than this.

**Pull request merged**
