### PR TITLE
Ability to add custom songs to story menu weeks without changing the code

### PR DESCRIPTION
**Pull request by bdidk235**
yeah, it might need to be changed to work better.

### CODE REVIEW

**Comment by y579** [comment]
It doesn't matter anyway because you still need to compile

**Comment by y579** [comment]
This WILL be closed

**Comment by bdidk235** [comment]
sure

**Comment by napstaa967** [comment]
main problem there's rn on the game code is that for some reason you cannot add custom songs via the precompiled version, you have to recompile it, even if you only have to add the data, songs, and the freeplay entry, it just crashes on the precompiled and loads on the recompiled

but yeah adding custom story week songs is a good idea

**Comment by isakube** [comment]
this is literally pointless because you can't create songs on precompile

**Comment by napstaa967** [comment]
> this is literally pointless because you can't create songs on precompile

iirc kade said on one of the closed issues that it is possible to add custom songs on precompiled but it still doesn't work

its either a bug or a missing feature

**Comment by ghost** [comment]
> > this is literally pointless because you can't create songs on precompile
> 
> iirc kade said on one of the closed issues that it is possible to add custom songs on precompiled but it still doesn't work
> 
> its either a bug or a missing feature

it IS possible to add songs on compiled binaries, the reason it doesnt work because the way OpenFL handles assets is by referencing it from the manifest embedded assets library (the manifest folder in the game). It's only useful when you compile to HTML5 and mobile devices, but kinda useless on desktops because you can read them directly anyways using the `fromFile` function.

In conclusion, yes, it's possible, but the asset system needs a rewrite.

**Pull request closed without merging**
