### PR TITLE
Toasters toast toast

### PR DESCRIPTION
**Pull request by Spel0**
Some fixes

### CODE REVIEW

**Comment by raf13lol** [comment]
why that name??? note: toasters toast toast

**Comment by Spel0** [comment]
> why that name???

Why not?

**Comment by raf13lol** [comment]
understandable, have a great day

**Comment by Spel0** [comment]
Drafting it cuz Github is having issues and won't push my recent commit to this PR

**Comment by Spel0** [comment]
Ok it works now

**Review by raf13lol — APPROVED** [review]
i think it works it looks good so yes

**Pull request merged**
