### PR TITLE
No more senpai infront of spirit's portrait. 

### LINKED ISSUE #1022: Throns dialouge show's senpai's sprite behind spirit
This was on windows and on version 1.5.4

### PR DESCRIPTION
**Pull request by ACardboardBox1**
Self-exploratory, fixes #1022

### CODE REVIEW

**Comment by ACardboardBox1** [comment]
Wait wait hold up i think im doing this wrong fúck

**Comment by ACardboardBox1** [comment]
#pain

**Comment by ACardboardBox1** [comment]
Imma close this to rework on tomorrow cuz I'm being a bit stupid

**Comment by isakube** [comment]
ever heard of draft prs

**Comment by ACardboardBox1** [comment]
> 
> 
> ever heard of draft prs

this was rushed and i didnt know how to do a draft pr, so imma just leave this closed and redo it lol

**Pull request closed without merging**
