### PR TITLE
Dialogue for Week 1-5 + Tutorial

### PR DESCRIPTION
**Pull request by Swapper1**
Due to FNF Restored source code has not been released unless they ask for permission to use it, we gonna need the dialogues for Week 1-5 including Tutorial like in FNF Restored. But it has two different animations, will contains the normal (like in week 6) and the static animation. This will also included the different expression such as "bf-scare" and "gf-crying" can be used.

### CODE REVIEW

**Comment by isakube** [comment]
~~why is this a fucking pull request~~
edit: draft it, sorry

**Comment by Jaduplex** [comment]
No.

**Comment by napstaa967** [comment]
1. did you ask for permission to use the added week 2-5 dialogue
2. draft it if its incomplete
also adding just ":character name:" to the dialogue text wont make the portraits pop up, they're linked to dialoguebox.hx and are hardcoded to the song, you have to use :dad:

**Comment by Futuremappermydud** [comment]
no

**Comment by isakube** [comment]
this pr rolled a Nat 1 in at least ~~one~~ two categories lol

**Comment by ACardboardBox1** [comment]
1. The dialogue isnt needed imo, it's useless.
2. The character names like "pico-angry" and shit arent just gonna work cuz they needed to be hardcoded in, just like napsta said.
3. why
4. there's other pull requests being added too lol

**Comment by napstaa967** [comment]
> 1. The dialogue isnt needed imo, it's useless.
> 2. The character names like "pico-angry" and shit arent just gonna work cuz they needed to be hardcoded in, just like napsta said.
> 3. why
> 4. there's other pull requests being added too lol

and the required playstate.hx and dialoguebox.hx code is missing on this pr

**Review by RagdollClash — CHANGES_REQUESTED** [review]
why is it only the end songs, and why is the dialogue so crude?

also just adding the dialogue files is completely useless because as what others have pointed out:
1. they are never loaded in PlayState
2. even if they are loaded, the necessary assets and code are not there

**Comment by napstaa967** [comment]
ok so all the problems with this:
1. there's no reason at all to add the dialogue
2. clearly, you don't know how to add custom textboxes
2.1. missing dialoguebox.hx code for the textboxes 
3. missing playstate.hx code to link txt files to songs
4. missing playstate.hx code to execute cutscenes
5. where are the images
6. using :mom:, :gf: and :skid:/:pump: wont work on normal code, the dialogue text is hardcoded to use :dad: and :bf: so you would need to modify the code to add the new icons
7. this is missing a lot of songs

so yeah

draft or close this pr because its clearly missing A LOT of stuff

**Review by napstaa967 — CHANGES_REQUESTED** [review]
ok so first:
rename all the instances of the second character (aka :parentsDad:, :dearest:, :monsterChristmas) to just :dad:, this is how the game works for now unless someone makes the textbox a per-character image instead of per-track

second: rename all the instances of boyfriend to :bf:

third: add the images

**Comment by napstaa967** [comment]
ok i think i figured a way to make this thing work with the custom characters n stuff

will try by myself then submit changes

**Comment by dummmmdum** [comment]
One thing you could do is use the unused official dialogue for Tutorial and Week 1 and drop everything else from FNF restored, I guess custom expressions would be useful

**Comment by napstaa967** [comment]
> One thing you could do is use the unused official dialogue for Tutorial and Week 1 and drop everything else from FNF restored, I guess custom expressions would be useful

i need portraits for stuff so im just gonna use cropped character sprites

**Pull request closed without merging**
