### PR TITLE
Delete BeatBattle

### PR DESCRIPTION
**Pull request by ACrazyTown**
It has been removed from the official Funkin' source, it's empty and it does absolutely nothing.

### CODE REVIEW

**Comment by isakube** [comment]
imagine making a blank file that's never mentioned ANYWHERE in the code, and leaving it in a public repository, untouched for like half a year.

can't relate

btw this might've originally been what PlayState is, guessing from the file name. kinda interesting-ish

**Comment by ACrazyTown** [comment]
> imagine making a blank file that's never mentioned ANYWHERE in the code, and leaving it in a public repository, untouched for like half a year.
> 
> can't relate
> 
> btw this might've originally been what PlayState is, guessing from the file name. kinda interesting-ish

I suppose it was supposed to be that fighting mechanic but ionno

I dont see a point to leave it in though

**Comment by ghost** [comment]
Maybe it made the beatboxing in Fresh work before they just did it in Inst
There is, in the Exclude, a sound file for one beatbox

**Comment by isakube** [comment]
> There is, in the Exclude, a sound file for one beatbox

yep

perhaps we could transfer this to a discussion? because i really like theorizing and i wanna keep the pr convo limited to the pr lol

**Pull request merged**
