### PR TITLE
Score Bar fix + toggleable health on Score Bar

### LINKED ISSUE #674: Enhancement: health on accuracy display
it would be awesome if there is a health option on accuracy, idk if its a good idea

### LINKED ISSUE #841: Bug Report: if NPS is enabled but Accuracy is disabled, only Score will show
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.2 + #840 + #842
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
go into settings enable NPS and disable Accuracy
## Please describe your issue. Provide extensive detail and images if possible.
if NPS is enabled but Accuracy is disabled, only Score will show

image

image

### PR DESCRIPTION
**Pull request by Lucky-56**
(Adds) Fixes #674 
Fixes #841

### CODE REVIEW

**Review by isakube — CHANGES_REQUESTED** [review]
wait i obviously don't know how comments work but ok

fix the typos lol `class HealthDisplyOption extends Option`
still functional, it's just idk

**Comment by Kade-github** [comment]
I absolutely despise health percentage. good pr, but I hate the feature.

**Comment by puyoxyz** [comment]
KadeDev moment

**Comment by isakube** [comment]
KadeDev moment

**Pull request closed without merging**
