### PR TITLE
Character Icons in ChartingState now match song's characters

### PR DESCRIPTION
**Pull request by Jaduplex**
just kinda been bugging me for a while

### CODE REVIEW

**Comment by Jaduplex** [comment]
sorry about the excess merges its just stuff from my master branch

**Comment by Jaduplex** [comment]
i swear if it still throws a null reference exception with all my fixes i will commit a war crime

**Comment by Kade-github** [comment]
bro theres so many commits.

**Comment by Jaduplex** [comment]
sorry most are just prs being merged from master here

**Pull request merged**
