### PR TITLE
bugfixes, quality of life, and aesthetics

### PR DESCRIPTION
**Pull request by RagdollClash**
- [QoL] animationdebug goes back to playstate instead of mainmenu (you access it from playstate anyways)
- [QoL] add outline to animdebug text (easier to read across bright background)
- [QoL] save to offset file instead of copying to clipboard (hotkey is now CTRL+S)
2021-08-23_22-52-21_Kade_Engine
- [QoL] show song multiplier next to the song name (hopefully doesn't show at default speed)
2021-08-23_22-47-21_Kade_Engine
- [FIX] fix timing of missnotes 2 and 3
- [AESTHETIC] add pixel variants of missnote (only plays with pixel note skin)
- [FIX] fix train sfx not playing every time it passes by
- [FIX] remove leftover volume changes from lumun dare version
- [AESTHETIC] port over dancing changes from the SiIvaGunner ripping builds (also modified to affect gameplaycustomize and storymode states)
- [FIX] prevent rate on freeplay menu showing a long ass decimal value
- [FIX] fix animation speed for letters and main menu options
- [FIX] fix animations for non-bf characters over player 1 (the issue where they constantly go back to their idle)

### CODE REVIEW

**Review by somefnfplayerlol — APPROVED** [review]
oh shit this epic
edit: i always hated how boyfriend's code used `playAnim('idle')` rather than `dance()`

**Comment by RagdollClash** [comment]
marking as draft to make one more change

**Comment by RagdollClash** [comment]
sorry for compiling so many changes into one PR, please let me know if i should split them up

**Comment by raf13lol** [comment]
dude this insane you got the check working????????? kade please merge this

**Pull request merged**
