### PR TITLE
Added QWOP and Spread (ZX12) control schemes

### PR DESCRIPTION
**Pull request by CarsonKompon**
Changed `FlxG.save.data.dfjk` from a bool to an int. Saving still works and will also load properly if controls were already DFJK before this.

0 = WASD
1 = DFJK
2 = QWOP
3 = Spread (ZX12 (The only option))

### CODE REVIEW

**Comment by theDetourist** [comment]
Don't support it, Week 7 is bringing custom keybinds so this'll become obsolete.

**Comment by CarsonKompon** [comment]
> Don't support it, Week 7 is bringing custom keybinds so this'll become obsolete.

While this is true, we have no idea when Week 7 will release, so until then this is the best we can get :)

**Comment by isakube** [comment]
> While this is true, we have no idea when Week 7 will release, so until then this is the best we can get :)

When the Newgrounds page for fnf gets 2nd or 1st place on search results. but uhhh it's on the third page currently

**Comment by Kade-github** [comment]
im just gonna make my own keybinds lol!

**Pull request closed without merging**
