### PR TITLE
Move the Modchart wiki to the website

### PR DESCRIPTION
**Pull request by puyoxyz**
- Title
- Fix formatting so jekyll markdown thing doesn't piss and cry

### CODE REVIEW

**Comment by Jaduplex** [comment]
1. should be merging into master, not stable. probably just an old pr tho
2. you haven't committed to this in 28 days. are you still working on it?

**Comment by isakube** [comment]
> 1. should be merging into master, not stable. probably just an old pr tho

That only applies to source code. Pretty sure master doesn't even get github-pages checks.

> 2. you haven't committed to this in 28 days. are you still working on it?

Yeahhh I go no idea what's happening. puyo said they were taking a break though so

**Comment by raf13lol** [comment]
what happened here? is anyone working on this still??

**Comment by isakube** [comment]
yo puyo the fuck happend lol

**Pull request closed without merging**
