### PR TITLE
Week 6 static arrows fix + alt anims for BF and Opponent

### PR DESCRIPTION
**Pull request by Spel0**
Fixes week 6 static arrows crashing the game when loading them outside of week 6 songs

Plus fixed some charting menu issues

### CODE REVIEW

**Review by raf13lol — APPROVED** [review]
yes this good for my bad computer bros

**Review by bdidk235 — APPROVED** [review]
approved

**Review by bdidk235 — APPROVED** [review]
reapproved

**Review by Mrnoob467 — APPROVED** [review]

**Comment by Spel0** [comment]
Kade please look into this PR or else i'm gonna turn this into my features wish list type of PR soon😂

**Comment by Kade-github** [comment]
there are conflicts here because half the shit in the charter you did, I already did.

also STOP USING updateGrid(); IT CAUSES UNESSACARY LAG IN THE EDITOR AND YOU CAN JUST MODIFY THE SHOWN NOTES >:((((

**Comment by Spel0** [comment]
> there are conflicts here because half the shit in the charter you did, I already did.

k i'm just gonna leave only new charting features and let you handle other things lol

**Pull request merged**
