### PR TITLE
Added A New Option - Color The Health Bar Depending On The Character! And Appveyor (partially) Has Been Fixed!

### PR DESCRIPTION
**Pull request by raf13lol**
This Is Automatically On By Default. I Could Need Some Suggestions For The Color Behind The Spooky Kids. I Have Put It To Orange For Now And Senpai's Color Is Pink For Now. Thanks For Reading! The .yml Has Been Fixed With Adding - haxelib git hxvm-luajit https://github.com/KadeDev/hxvm-luajit! And If You Are Saying That Mac-OS And Linux Does Not Need This, I Am Getting It Ready For When It Does Need It!

### CODE REVIEW

**Comment by brosomethingwrongwithyothing** [comment]
what??? why did check fail??

**Review by NukeThief — APPROVED** [review]

**Comment by isakube** [comment]
spooky kids could be the brown in Pump or the grey in Skid

**Comment by DamianBossPL** [comment]
I have also done this:
`

            var p2color:FlxColor = 0xFFFF0000;
		var p1color:FlxColor =  0xFF66FF33;

		switch (dad.curCharacter)
		{
			case 'bf' | 'bf-car' | 'bf-christmas' | 'bf-pixel' | 'bf-holding-gf':
				p2color = 0xFF31b0d1;
			case 'gf':
				p2color = 0xFFa5004d;
			case 'dad':
				p2color = 0xFFaf66ce;
			case 'spooky':
				p2color = 0xFFb4b4b4;
			case 'monster' | 'monster-christmas':
				p2color = 0xFFf3ff6e;
			case 'pico':
				p2color = 0xFFb7d855;
			case 'mom' | 'mom-car':
				p2color = 0xFFd8558e;
			case 'parents-christmas':
				p2color = 0xFFa5004d;
			case 'senpai' | 'senpai-angry':
				p2color = 0xFFffaa6f;
			case 'spirit':
				p2color = 0xFFff3c6e;
			case 'dbpl':
				p2color = 0xFF0048ab;
			case 'tankman':
				p2color = 0xFF303030;
		}
		switch (boyfriend.curCharacter)
		{
			case 'bf' | 'bf-car' | 'bf-christmas' | 'bf-pixel' | 'bf-holding-gf':
				p1color = 0xFF31b0d1;
			case 'gf':
				p1color = 0xFFa5004d;
			case 'dad':
				p1color = 0xFFaf66ce;
			case 'spooky':
				p1color = 0xFFb4b4b4;
			case 'monster' | 'monster-christmas':
				p1color = 0xFFf3ff6e;
			case 'pico':
				p1color = 0xFFb7d855;
			case 'mom' | 'mom-car':
				p1color = 0xFFd8558e;
			case 'parents-christmas':
				p1color = 0xFFa5004d;
			case 'senpai' | 'senpai-angry':
				p1color = 0xFFffaa6f;
			case 'spirit':
				p1color = 0xFFff3c6e;
			case 'dbpl':
				p1color = 0xFF0048ab;
			case 'tankman':
				p2color = 0xFF303030;
		}
		

		healthBar.createFilledBar(p2color,  p1color);
		// healthBar
		add(healthBar);var p2color:FlxColor = 0xFFFF0000;
		var p1color:FlxColor =  0xFF66FF33;

		switch (dad.curCharacter)
		{
			case 'bf' | 'bf-car' | 'bf-christmas' | 'bf-pixel' | 'bf-holding-gf':
				p2color = 0xFF31b0d1;
			case 'gf':
				p2color = 0xFFa5004d;
			case 'dad':
				p2color = 0xFFaf66ce;
			case 'spooky':
				p2color = 0xFFb4b4b4;
			case 'monster' | 'monster-christmas':
				p2color = 0xFFf3ff6e;
			case 'pico':
				p2color = 0xFFb7d855;
			case 'mom' | 'mom-car':
				p2color = 0xFFd8558e;
			case 'parents-christmas':
				p2color = 0xFFa5004d;
			case 'senpai' | 'senpai-angry':
				p2color = 0xFFffaa6f;
			case 'spirit':
				p2color = 0xFFff3c6e;
			case 'dbpl':
				p2color = 0xFF0048ab;
			case 'tankman':
				p2color = 0xFF303030;
		}
		switch (boyfriend.curCharacter)
		{
			case 'bf' | 'bf-car' | 'bf-christmas' | 'bf-pixel' | 'bf-holding-gf':
				p1color = 0xFF31b0d1;
			case 'gf':
				p1color = 0xFFa5004d;
			case 'dad':
				p1color = 0xFFaf66ce;
			case 'spooky':
				p1color = 0xFFb4b4b4;
			case 'monster' | 'monster-christmas':
				p1color = 0xFFf3ff6e;
			case 'pico':
				p1color = 0xFFb7d855;
			case 'mom' | 'mom-car':
				p1color = 0xFFd8558e;
			case 'parents-christmas':
				p1color = 0xFFa5004d;
			case 'senpai' | 'senpai-angry':
				p1color = 0xFFffaa6f;
			case 'spirit':
				p1color = 0xFFff3c6e;
			case 'dbpl':
				p1color = 0xFF0048ab;
			case 'tankman':
				p2color = 0xFF303030;
		}
		

		healthBar.createFilledBar(p2color,  p1color);
		// healthBar
		add(healthBar);
`

**Comment by raf13lol** [comment]
> I have also done this:
> `
> 
> ```
>         var p2color:FlxColor = 0xFFFF0000;
> 	var p1color:FlxColor =  0xFF66FF33;
> 
> 	switch (dad.curCharacter)
> 	{
> 		case 'bf' | 'bf-car' | 'bf-christmas' | 'bf-pixel' | 'bf-holding-gf':
> 			p2color = 0xFF31b0d1;
> 		case 'gf':
> 			p2color = 0xFFa5004d;
> 		case 'dad':
> 			p2color = 0xFFaf66ce;
> 		case 'spooky':
> 			p2color = 0xFFb4b4b4;
> 		case 'monster' | 'monster-christmas':
> 			p2color = 0xFFf3ff6e;
> 		case 'pico':
> 			p2color = 0xFFb7d855;
> 		case 'mom' | 'mom-car':
> 			p2color = 0xFFd8558e;
> 		case 'parents-christmas':
> 			p2color = 0xFFa5004d;
> 		case 'senpai' | 'senpai-angry':
> 			p2color = 0xFFffaa6f;
> 		case 'spirit':
> 			p2color = 0xFFff3c6e;
> 		case 'dbpl':
> 			p2color = 0xFF0048ab;
> 		case 'tankman':
> 			p2color = 0xFF303030;
> 	}
> 	switch (boyfriend.curCharacter)
> 	{
> 		case 'bf' | 'bf-car' | 'bf-christmas' | 'bf-pixel' | 'bf-holding-gf':
> 			p1color = 0xFF31b0d1;
> 		case 'gf':
> 			p1color = 0xFFa5004d;
> 		case 'dad':
> 			p1color = 0xFFaf66ce;
> 		case 'spooky':
> 			p1color = 0xFFb4b4b4;
> 		case 'monster' | 'monster-christmas':
> 			p1color = 0xFFf3ff6e;
> 		case 'pico':
> 			p1color = 0xFFb7d855;
> 		case 'mom' | 'mom-car':
> 			p1color = 0xFFd8558e;
> 		case 'parents-christmas':
> 			p1color = 0xFFa5004d;
> 		case 'senpai' | 'senpai-angry':
> 			p1color = 0xFFffaa6f;
> 		case 'spirit':
> 			p1color = 0xFFff3c6e;
> 		case 'dbpl':
> 			p1color = 0xFF0048ab;
> 		case 'tankman':
> 			p2color = 0xFF303030;
> 	}
> 	
> 
> 	healthBar.createFilledBar(p2color,  p1color);
> 	// healthBar
> 	add(healthBar);var p2color:FlxColor = 0xFFFF0000;
> 	var p1color:FlxColor =  0xFF66FF33;
> 
> 	switch (dad.curCharacter)
> 	{
> 		case 'bf' | 'bf-car' | 'bf-christmas' | 'bf-pixel' | 'bf-holding-gf':
> 			p2color = 0xFF31b0d1;
> 		case 'gf':
> 			p2color = 0xFFa5004d;
> 		case 'dad':
> 			p2color = 0xFFaf66ce;
> 		case 'spooky':
> 			p2color = 0xFFb4b4b4;
> 		case 'monster' | 'monster-christmas':
> 			p2color = 0xFFf3ff6e;
> 		case 'pico':
> 			p2color = 0xFFb7d855;
> 		case 'mom' | 'mom-car':
> 			p2color = 0xFFd8558e;
> 		case 'parents-christmas':
> 			p2color = 0xFFa5004d;
> 		case 'senpai' | 'senpai-angry':
> 			p2color = 0xFFffaa6f;
> 		case 'spirit':
> 			p2color = 0xFFff3c6e;
> 		case 'dbpl':
> 			p2color = 0xFF0048ab;
> 		case 'tankman':
> 			p2color = 0xFF303030;
> 	}
> 	switch (boyfriend.curCharacter)
> 	{
> 		case 'bf' | 'bf-car' | 'bf-christmas' | 'bf-pixel' | 'bf-holding-gf':
> 			p1color = 0xFF31b0d1;
> 		case 'gf':
> 			p1color = 0xFFa5004d;
> 		case 'dad':
> 			p1color = 0xFFaf66ce;
> 		case 'spooky':
> 			p1color = 0xFFb4b4b4;
> 		case 'monster' | 'monster-christmas':
> 			p1color = 0xFFf3ff6e;
> 		case 'pico':
> 			p1color = 0xFFb7d855;
> 		case 'mom' | 'mom-car':
> 			p1color = 0xFFd8558e;
> 		case 'parents-christmas':
> 			p1color = 0xFFa5004d;
> 		case 'senpai' | 'senpai-angry':
> 			p1color = 0xFFffaa6f;
> 		case 'spirit':
> 			p1color = 0xFFff3c6e;
> 		case 'dbpl':
> 			p1color = 0xFF0048ab;
> 		case 'tankman':
> 			p2color = 0xFF303030;
> 	}
> 	
> 
> 	healthBar.createFilledBar(p2color,  p1color);
> 	// healthBar
> 	add(healthBar);
> ```
> 
> `

yo could i -ahem *borrow* that for my pr

**Comment by raf13lol** [comment]
> spooky kids could be the brown in Pump or the grey in Skid

maybe i could make it random?

**Comment by raf13lol** [comment]
i was trash back then lmao

**Pull request merged**
