### PR TITLE
Chart Editor Guide

### PR DESCRIPTION
**Pull request by isakube**
yayyyy if this gets merged 2/4 are done

### CODE REVIEW

**Comment by puyoxyz** [comment]
add link to guides index and pls deploy the branch on github pages so we can preview what it looks like on the site

edit: nevermind about the second part u changed the url

edit: Okay I Don't Know What's Happening can u give link
image

**Comment by isakube** [comment]
yeah i'm getting that too, weird. idk why that happens, though. everything should be correct, but uhh yeah it doesn't show up on my side either. huh

**Comment by isakube** [comment]
changed fork name back to Funkin btw
and file name it charting-state now

**Comment by isakube** [comment]
HAHA I FIGURED IT OUT IM SUCH AN IDIOT
Screen Shot 2021-05-16 at 1 25 56 PM
`patch-1` is the charting guide branch btw, it used to be on `week-guide`

**Review by puyoxyz — CHANGES_REQUESTED** [review]
Rename file to "charting" or "chart-editor", even though charting-state is the name of the state that's not the name you actually use in the guide, so it's better for it to be one of those

"Requirements" section: not needed, so why have it? Probably delete it.

"Key": rename to "Table of contents"

"simply begin a level in Freeplay Mode" you can access the chart editor from story mode too;;;

"To test the chart’s sync," clarify what this means, like "To test the chart's sync (see if it's aligned with the audio)" 

"Alternate Animation is used exclusively for the Mom and Dad from Week 5, but if your character has an Alternate Animation, you can tick this checkbox to use it instead of the normal animation." Clarify that this checkbox applies per-section, this seems like it means it applies for the whole chart

Index: change links to `{{site.url}}guides/weeks`, `{{site.url}}guides/charting-state` (or whatever you end up making the name of the charting guide), {{site.url}} gets turned into `https://kadedev.github.io/Kade-Engine/` by Liquid.

request re-review once done? or that might get done automatically by github when you mark it as ready for review idk

i know this is a draft but like yeah;;;; early feedback

and so that i dont get confused trying to find the link again imma leave it here: https://prokube.github.io/Funkin/guides/charting-state

**Comment by isakube** [comment]
https://prokube.github.io/Funkin/guides/charting fixed the url name, and i did the stuff

**Review by puyoxyz — APPROVED** [review]

**Comment by isakube** [comment]
100th pull request if we're counting based on when it was resolved :+1:

**Pull request merged**
