### PR TITLE
made a setup file

### PR DESCRIPTION
**Pull request by Jotaro-Gaming**
it takes time to copy everything one by one so i made this file to save some time for people

### CODE REVIEW

**Comment by Jotaro-Gaming** [comment]
tell me if i did something wrong lmao

**Comment by Jotaro-Gaming** [comment]
kade pls merge this

**Comment by Jotaro-Gaming** [comment]
@KadeDev pls merge thissssssssssss

**Comment by EliteMasterEric** [comment]
Why the hell would you add a link to a google drive of a batch file instead of just... putting it in the repo...

That Visual Studio community installer is slick tho

EDIT: Also APIStuff.hx just needs to be removed from the repo entirely, it was only ever used for the Newgrounds code, which was removed completely in #2183.

**Comment by Jotaro-Gaming** [comment]
> Why the hell would you add a link to a google drive of a batch file instead of just... putting it in the repo...
> 
> That Visual Studio community installer is slick tho
> 
> EDIT: Also APIStuff.hx just needs to be removed from the repo entirely, it was only ever used for the Newgrounds code, which was removed completely in #2183.

ok ill remove the apistuff file but how do i put it in the repo

**Comment by Jotaro-Gaming** [comment]
now in #2391

**Pull request closed without merging**
