### PR TITLE
Editor grid sub-divisions, separate editor options window & more

### PR DESCRIPTION
**Pull request by GithubSPerez**
Much needed editor option is here
image

### CODE REVIEW

**Comment by Kade-github** [comment]
banger commit babe

**Comment by ACardboardBox1** [comment]
> 
> 
> banger commit babe

babe!??!?!?!?!?!?/1!?!/!/!/1/1/11/11./1/1!?.1/!.!./!/!1/1/1/1/1 🤨

**Comment by GithubSPerez** [comment]
😳

**Comment by ACardboardBox1** [comment]
> 
> 
> 😳

you wanna tell me something

**Pull request merged**
