### PR TITLE
Add customizable tweens to modcharting

### PR DESCRIPTION
**Pull request by ItzFireable**
Add FlxEase tweens as an available option for each modchart tween function. 

Default values for each function are set to what they were before.

(please ignore the massive switch case, i couldn't find a better way lmfao)

### CODE REVIEW

**Comment by ItzFireable** [comment]
Made them optionable, forgot about that. Old modcharts don't break now.

**Comment by Kade-github** [comment]
please resolve the conflicts.

**Comment by ACardboardBox1** [comment]
what is even happening in this pr

**Comment by Kade-github** [comment]
I dont feel like this is ever getting merged without da conflicts gone. Remake a pull on master again or smth

**Pull request closed without merging**
