### PR TITLE
Adding Test Renamed Freestyle To The Freeplay / Story Menu note: test is in the files not a custom song :(

### PR DESCRIPTION
**Pull request by raf13lol**
I Added Test- I Mean Freestyle Because I Was Sad That The Song Was Such A Bop But Not In The Official Kade Engine, So I Added It! 
edit: it is in the game files stop saying it was a custom song

### CODE REVIEW

**Comment by raf13lol** [comment]
yay :) it passed the checks

**Comment by isakube** [comment]
> Delete assets/preload/data directory
:flushed:

**Comment by raf13lol** [comment]
dont worry i added it back @prokube

**Comment by napstaa967** [comment]
stop closing and reopening it just draft it

**Comment by raf13lol** [comment]
why?

**Comment by napstaa967** [comment]
> why?

if you found a bug or this is still in progress just make it a draft instead of closing and reopening

**Comment by raf13lol** [comment]
umm its more so that i think its staying forever when the check is finished so i close it but then its not so i think i have to wait for the new update of 1.6.2 then i can close it

**Comment by CyndaquilDAC** [comment]
We're not adding custom songs to kade engine.

**Comment by raf13lol** [comment]
the reason i marked it as a draft because i was testing something out but it crashed but dont worry its not the same code

**Comment by Spel0** [comment]
What does test song has to do with custom made freestyle song even?

**Comment by raf13lol** [comment]
i just renamed test to freestyle

**Comment by raf13lol** [comment]
oops

**Comment by Spel0** [comment]
> i just renamed test to freestyle

Yea, and put entirely different song, very clever

**Comment by raf13lol** [comment]
You want proof? This Hasn't been merged yet so download from https://github.com/brosomethingwrongwithyothing/Kade-Engine/tree/master/assets/songs/freestyle and then download from here https://github.com/KadeDev/Kade-Engine/blob/stable/assets/songs/test/Inst.ogg note: they are ogg files then tell me the difference

**Comment by Spel0** [comment]
> You want proof? This Hasn't been merged yet so download from https://github.com/brosomethingwrongwithyothing/Kade-Engine/tree/master/assets/songs/freestyle and then download from here https://github.com/KadeDev/Kade-Engine/blob/stable/assets/songs/test/Inst.ogg note: they are ogg files then tell me the difference

Commit that last one was added in literally says that it's stolen from fps plus 💀 

Btw if you don't know, fps plus is not vanilla game engine

**Comment by raf13lol** [comment]
i made use of what was in the files edit: i didnt even know because kade dev added it

**Comment by Spel0** [comment]
Up to Kade then ig if he wants it to be merged or not, but I would say that adding it to tutorial playlist was probably an overkill

**Comment by raf13lol** [comment]
if he wants i can remove it just leave it in the freeplay menu

**Comment by raf13lol** [comment]
Appveyor checks are so buggy this is not 50 GBs in size

**Comment by raf13lol** [comment]
let me retry this check

**Comment by raf13lol** [comment]
WHYYYYY

**Comment by napstaa967** [comment]
> WHYYYYY

ignore it

appveyor stupid

**Comment by raf13lol** [comment]
ok

**Comment by Jaduplex** [comment]
can we close this? kade'll do it himself eventually.

**Comment by raf13lol** [comment]
> can we close this? kade'll do it himself eventually.

why?

**Comment by raf13lol** [comment]
ok fine

**Comment by ACardboardBox1** [comment]
what the fuck even happened here

**Comment by ACardboardBox1** [comment]
plus imo this really isnt needed

**Pull request closed without merging**
