### PR TITLE
Remove Newgrounds Code

### PR DESCRIPTION
**Pull request by EliteMasterEric**
Newgrounds doesn't let people upload mods, so this is all dead code and `haxelib install newgrounds` is pointless.

Remove `NGio.hx`, all code references to Newgrounds and medals, and the `newgrounds` dependency.

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
awww shit git broke this hand on

**Comment by somefnfplayerlol** [comment]
dude dont merge into stable

**Comment by Spel0** [comment]
tostable

**Comment by isakube** [comment]
*ahem*

STOP MERGING INTO STABLE! I'M TIRED OF SEEING IT! My friends on GitHub merge to stable, on Discord it's fuckin' stable, I was in a server, right? And AAAALL THE MODDERS WERE MERGING INTO STABLE. I-I-I SHOWED MY KADE ENGINE PR TO MY GIRLFRIEND, AND I CHANGED THE TARGET BRANCH TO STABLE, AND I SAID "Hey babe, when the PR merges to stable!" HAHAHAHAHA, DING DING DING DING DInG DING DING. DIDIDING. *inhale* AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

###### Feel free to copypasta this :)

**Comment by EliteMasterEric** [comment]
Fixed by not merging into stable like a D U M B A S S

**Pull request merged**
