### PR TITLE
Offset info text now updates properly

### PR DESCRIPTION
**Pull request by theDetourist**
The offset info text was only updating whenever you changed menu selections or entered a category.

### CODE REVIEW

**Comment by Lucky-56** [comment]
yeah boi, let's go

**Comment by Lucky-56** [comment]
Fixes #799 
Fixes #865

**Comment by theDetourist** [comment]
> 
> 
> Fixes #799
> Fixes #865

<strike>Right now it only fixes the second, I'm still looking at the first one though.</strike>

Both are now fixed.

**Review by ACardboardBox1 — APPROVED** [review]
looks good

**Pull request merged**
