### PR TITLE
blue healthBar

### PR DESCRIPTION
**Pull request by Jotaro-Gaming**
instead of the defualt green on the health bar it syncs with bf icons
hope it gets merged!

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
🌈 Stop making pull requests to stable 🌈 

Also changes to healthbar logic were already made in #2115.

**Comment by somefnfplayerlol** [comment]
*inhale* STOP MERGING TO STABLE, I'M TIRED OF SEEING IT!

**Comment by RagdollClash** [comment]
this PR also overrides every combination to be the same one

**Comment by Jotaro-Gaming** [comment]
> 🌈 Stop making pull requests to stable 🌈
> 
> Also changes to healthbar logic were already made in #2115.

i didnt know thanks for telling me

**Pull request closed without merging**
