### PR TITLE
Week 7 recharts

### PR DESCRIPTION
**Pull request by theDetourist**
Compliant with the new unhardcoded shit too.

Also decided to add default offset files and two cases where they were needed on Week 6 due to inconsistencies with the Global Offset.

### CODE REVIEW

**Comment by Kade-github** [comment]
epic

**Comment by isakube** [comment]
gaming

**Comment by ghost** [comment]
wait is this... week 7 on ke

**Comment by theDetourist** [comment]
> 
> 
> wait is this... week 7 on ke

No.

**Pull request merged**
