### PR TITLE
Miss Sound and Vocals Mute option into settings

### PR DESCRIPTION
**Pull request by Spel0**
Not sure why it wasn't implemented yet, but here we are. Does what the name suggests, Miss Sound can be turned on and off to not be played on miss, and mute vocal option either allows vocal to continue playing on miss or mutes it like we have it right now.

### CODE REVIEW

**Comment by ACardboardBox1** [comment]
(oh hey it's the dude from the discord)

we needed this.

**Comment by Spel0** [comment]
> (oh hey it's the dude from the discord)
> 
> we needed this.

I wonder why such feature didn't had PR before or why kade didn't made it yet. Seems easy to implement and I'm pretty sure a lot of people would like to have an option like this so they could vibe to the music, instead of hearing an obnoxious disk scratching or sudden music vocals going dark.

**Review by RagdollClash — COMMENTED** [review]
works as intended

tho IMHO I feel like it would be best to combine these two options together in addition to using the regular singing animation, similar to Project DIVA's "Vocals on Miss" option

**Comment by Spel0** [comment]
> tho IMHO I feel like it would be best to combine these two options together in addition to using the regular singing animation, similar to Project DIVA's "Vocals on Miss" option

I think in this case it would be better to introduce that with some kind of "practice mode", since you could get game over without even knowing that you miss a lot

Edit: But I do agree that if we combine those options then it would make more sense

**Review by ACardboardBox1 — APPROVED** [review]
Looks good, i think you should just make the option say Mute vocals and miss sounds

**Comment by Kade-github** [comment]
Idk about this one. Id rather wait till i get around to redoing options.

**Pull request closed without merging**
