### PR TITLE
Export license with game

### PR DESCRIPTION
**Pull request by suprstarrd**
This helps follow the Apache license terms, 4a:
> 4. Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
a. You must give any other recipients of the Work or Derivative Works a copy of this License; and
b. You must cause any modified files to carry prominent notices stating that You changed the files;
c. You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
d. If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.

4b and 4d will definitely take a bit more work, will make another PR for those.

### CODE REVIEW

**Review by isakube — APPROVED** [review]
yoooooooooo

**Comment by suprstarrd** [comment]
AppVeyor kind of just decided to do nothing for 20 minutes

**Comment by isakube** [comment]
> AppVeyor kind of just decided to do nothing for 20 minutes

It's probably waking up and needs some Folger's, it's barely 6AM where i'm at so I see where it's coming from lol

**Comment by suprstarrd** [comment]
lets gooooo it worked

image

**Comment by prokube** [comment]
> image

Mac user? pog?

**Comment by suprstarrd** [comment]
in what world does a linux build exceed a macOS build, and more importantly how did it get a 50gb artifact storage size

it does export though
image

downloading the windows artifact also shows `LICENSE.txt` in there

**Comment by Kade-github** [comment]
ye

**Pull request merged**
