### PR TITLE
Bf animations fix

### PR DESCRIPTION
**Pull request by Spel0**
[Before](https://www.youtube.com/watch?v=1XziqOJc6b0)

[After](https://www.youtube.com/watch?v=5SmF6GkDZoE)

### CODE REVIEW

**Review by Jaduplex — CHANGES_REQUESTED** [review]
I love you

**Comment by Jaduplex** [comment]
Oops

**Comment by Jaduplex** [comment]
I meant to approve changes not request them lol

**Review by Jaduplex — APPROVED** [review]
Love you

**Comment by Trayfellow** [comment]
ty

**Pull request merged**
