### PR TITLE
Adding practice mode

### PR DESCRIPTION
**Pull request by epicbobmanbob**
This adds a "Practice Mode" into the game which essentially means you cant die.
There is a catch. Your highscore doesn't save when you beat a song.

> you forgot to add
> defaults _in `KadeEngineData.hx`_
> and reset _in `Options.hx` at ResetSettings_

Ok will fix that!

### CODE REVIEW

**Review by Lucky-56 — CHANGES_REQUESTED** [review]
you forgot to add
defaults *in `KadeEngineData.hx`*
and reset *in `Options.hx` at ResetSettings*

**Comment by epicbobmanbob** [comment]
> and reset _in `Options.hx` at ResetSettings_

What do you mean by ResetSettings? There is no mention of it in `Options.hx`

**Comment by Lucky-56** [comment]
> 
> 
> > and reset _in `Options.hx` at ResetSettings_
> 
> What do you mean by ResetSettings? There is no mention of it in `Options.hx`

then update your source

EDIT: you're merging into stable... don't.
use `master` instead

**Comment by isakube** [comment]
> EDIT: you're merging into stable... don't.
> use `master` instead

THIS is why the default branch needs to be `master`. bc pull requests will default to trying to merge to the head branch, which is `stable`. ._.

**Review by isakube — CHANGES_REQUESTED** [review]
Perhaps add a toggle in the Pause Menu. Other than that, gaming

**Comment by epicbobmanbob** [comment]
How do I change the branch I am pulling from? (Sorry, I'm not good at pull requests)

**Comment by epicbobmanbob** [comment]
I will create a new request using master instead of stable.

**Pull request closed without merging**
