### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Micahiscoo**

### CODE REVIEW

**Comment by Spel0** [comment]
Master

**Comment by isakube** [comment]
lol wrong fork

**Comment by Micahiscoo** [comment]
okie sorry lol, still getting a hang of things

**Comment by napstaa967** [comment]
close this pr

**Review by raf13lol — APPROVED** [review]
yeah this isnt supposed to be a pr but i can say your code does work but still close this :/

**Comment by somefnfplayerlol** [comment]
uhhh...why are you adding nonsense to kade engine?

**Pull request closed without merging**
