### PR TITLE
Unhardcode GF Version, stages, and noteskins and make them loaded from chart

### PR DESCRIPTION
**Pull request by Jaduplex**
Nothing much to say. This is definitely the biggest pr I've ever made.

### CODE REVIEW

**Comment by haya3218** [comment]
Felt like instead of editing every single chart json to include a gfVersion parameter wasnt needed since it would be simple as adding a parameter to LoadingState.hx or Song.hx to make a check if the gfVersion in that json doesnt exist or is null.

Aka what the pr https://github.com/ninjamuffin99/Funkin/pull/767 did. 
lol

**Comment by Jaduplex** [comment]
> Felt like instead of editing every single chart json to include a gfVersion parameter wasnt needed since it would be simple as adding a parameter to LoadingState.hx or Song.hx to make a check if the gfVersion in that json doesnt exist or is null.
> 
> Aka what the pr [ninjamuffin99#767](https://github.com/ninjamuffin99/Funkin/pull/767) did.
> lol

the chart edits also include stages.

**Comment by haya3218** [comment]
> > Felt like instead of editing every single chart json to include a gfVersion parameter wasnt needed since it would be simple as adding a parameter to LoadingState.hx or Song.hx to make a check if the gfVersion in that json doesnt exist or is null.
> > Aka what the pr [ninjamuffin99#767](https://github.com/ninjamuffin99/Funkin/pull/767) did.
> > lol
> 
> the chart edits also include stages.

kewl but it would be a fallback to mod charts (aka b-sides not having that parameter) so you dont have to put them all in

**Comment by haya3218** [comment]
but other than that, good job lol

**Comment by RagdollClash** [comment]
for some reason, tab switching with TAB and TAB+SHIFT has become broken in this PR

**Comment by haya3218** [comment]
> for some reason, tab switching with TAB and TAB+SHIFT has become broken in this PR

Think thats caused with the new Assets tab

**Pull request merged**
