### PR TITLE
ModCore: Add proper Polymod support

### PR DESCRIPTION
**Pull request by EliteMasterEric**
This PR does the following:

* Create a new ModCore class, containing utility functions to properly initialize and run Polymod.
* Rework asset loading engine-wide to ensure all methods access `openfl.util.Assets`, which Polymod injects itself into.
* Reworked documentation to explain how to make mods, and added a custom KadeEngineLogo to the intro mod so you know mods are working.
* Moved songs from `data/` to `data/songs`. This is in preparation for future PRs, which will make other parts of the game more data driven to better support mods.
* Make some fixes to the Debug logging to ensure it can observe the mod loading process.

Additional notes:
* This PR is reliant on, and pending the merging off, the other pull requests I've made.
* My hope is that, with future PRs, we can add powerful features like the mod menu and scripting, but I want to get a simple PR up that allows for replacing and appending basic assets.

Attached is an example mod I made for testing, which ports the [Ena Skin Pack](https://gamebanana.com/mods/186934).
[Example Mod - Ena Skin Pack.zip](https://github.com/KadeDev/Kade-Engine/files/7169133/Example.Mod.-.Ena.Skin.Pack.zip)

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
Marked as draft pending merge of: #2233, #2252, #2253, #2257

**Review by isakube — APPROVED** [review]
everybody bow down quick before he denies us these masterpieces

also 90% of the changes are reformats lmaooo

**Comment by EliteMasterEric** [comment]
Lol I'll fix that in a minute

**Review by polybiusproxy — APPROVED** [review]
best pr i saw in my life

**Comment by EliteMasterEric** [comment]
PR has been rebased and is no longer reliant on #2233 or #2257.

It can be merged as desired.

**Comment by EliteMasterEric** [comment]
@KadeDev I am wondering about the state of this pull request. Its features are stable and build successfully. 

If you have issues with how this feature is coded, please provide a review and I will gladly resolve those issues.

If you do not think the PR is appropriate for Kade Engine (such as if you feel the feature does not fit your design intentions, or you feel the feature would require extensive effort to maintain) please let me know this as soon as you can so that I can develop plans for the future.

**Comment by Kade-github** [comment]
I think we are ready.

**Pull request merged**
