### PR TITLE
Animation Debug to Main Menu shortcut

### PR DESCRIPTION
**Pull request by Mrnoob467**
I got tired of closing the program every time I used the animation debugger, so I added a shortcut to the main menu by pressing enter. It should be useful for people like myself who want to offset multiple characters at a time. (I don't know why it says I changed the entire document when I literally just added a few lines of code) EDIT: FUCK I ACCIDENTALLY DELETED THE CONTRIBUTING FILE. (Ignore that please thankssss)

### CODE REVIEW

**Comment by isakube** [comment]
> (Ignore that pls)

we can't lol. re-add it

**Comment by ghost** [comment]
> (Ignore that please thankssss)

just revert the commit omegalul

**Comment by Mrnoob467** [comment]
OK I think I fixed it @prokube

**Comment by raf13lol** [comment]
@Mrnoob467 how do you access animation debug?

**Comment by Mrnoob467** [comment]
> @Mrnoob467 how do you access animation debug?

Same as it always was. 0 or 6 while playing a song.
0 for P1
6 for P2

**Comment by raf13lol** [comment]
@Mrnoob467  it doesnt work :/

**Review by raf13lol — APPROVED** [review]
idk on how to get to the animation debug but that does seem like it would work

**Comment by Burger-Gaming** [comment]
> idk on how to get to the animation debug but that does seem like it would work

you press 6 for the opponent, idk about bf tho

**Comment by Mrnoob467** [comment]
> idk on how to get to the animation debug but that does seem like it would work

Are you playing in debug mode? If not the animation debug state is locked.

**Comment by scintesto** [comment]
> > idk on how to get to the animation debug but that does seem like it would work
> 
> Are you playing in debug mode? If not the animation debug state is locked.

ok so how the hell do i set the debug flag or thing

**Comment by EliteMasterEric** [comment]
Implemented by #1914, this can be closed.

**Comment by raf13lol** [comment]
yes

**Pull request closed without merging**
