### PR TITLE
PLS KADE ENGINE, STOP DESTROYING YOUR ENGINE WITH USELESS STUFF

### PR DESCRIPTION
**Pull request by guizinhomartinez**
WHY THIS HAS BEING A THING FOR MORE THEN 3 VERSIONS AAAAAAAAAAAAAAAAAA (btw if you want to use this into your mod just ignore this stashed stuff this is my first PR)

### CODE REVIEW

**Comment by Jaduplex** [comment]
PLS GUIZINHOMARTINEZ SHUT UP AND MAKE ACTUALLY USEFUL PRS

**Comment by Spel0** [comment]
Did you seriously just removed timing text all together?

**Comment by guizinhomartinez** [comment]
yes for me it was a big thing ok?

**Comment by guizinhomartinez** [comment]
dont judge me tho this is my first pr, itill planing stuff

**Comment by Spel0** [comment]
> yes for me it was a big thing ok?

Why? Kade engine is literally **competitive engine**, if it wouldn't show timings each time you hit a note, it would just turn into casual engine lmao

**Comment by isakube** [comment]
this dude literally removed the timing text.

shut up.

**Comment by HiroMizuki** [comment]
yeah bud, i think the same
like, there's somethings on kade engine that makes the engine bad yknow

**Comment by ACardboardBox1** [comment]
just remove it in your own kade engines

or just make a pr of a option where you can turn it off

**Comment by Kade-github** [comment]
btw this isn't a useless feature. it shows you how far off you where on hitting a note, thats really useful.

**Comment by guizinhomartinez** [comment]
how the frick kadedev saw this shitty pull request

**Comment by isakube** [comment]
> how the frick kadedev saw this shitty pull request

yeah and closed it bc youre that bad

**Comment by guizinhomartinez** [comment]
yes

**Pull request closed without merging**
