### PR TITLE
clean up player strumming code + sustain clipping code

### PR DESCRIPTION
**Pull request by somefnfplayerlol**
as the title says.

### CODE REVIEW

**Comment by Kade-github** [comment]
resolve conflicts pls :)

**Comment by somefnfplayerlol** [comment]
stop arguing about this pr bruhSent from my Galaxy Tab A

**Comment by somefnfplayerlol** [comment]
sure

**Comment by somefnfplayerlol** [comment]
done per your pleasure

**Comment by somefnfplayerlol** [comment]
oh wait never mindSent from my Galaxy Tab A
-------- Original message --------From: Kade M ***@***.***> Date: 9/5/21  2:06 PM  (GMT-07:00) To: KadeDev/Kade-Engine ***@***.***> Cc: somefnfplayerlol ***@***.***>, Author ***@***.***> Subject: Re: [KadeDev/Kade-Engine] clean up player strumming code + sustain clipping code (#2015) 
resolve conflicts pls :)

**Comment by cah-keith-baker01** [comment]
> Conflicting files
> source/PlayState.hx

**Comment by somefnfplayerlol** [comment]
godammit github stop freezing im trying to resolve conflicts here

**Comment by somefnfplayerlol** [comment]
f this, im closing this and starting a new one

**Pull request closed without merging**
