### PR TITLE
Upgrade Haxe to latest (4.2.3).

### PR DESCRIPTION
**Pull request by EliteMasterEric**
Honestly I can't see what the problem was. Game builds and runs fine on my machine and GitHub actions come back okay.

4.2.3 came out in July whereas the build documentation was written in April, so maybe it's outdated and the issue is fixed.

@KadeDev Do you remember what the original issue was? Was it a build-time failure or a runtime failure?

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
Mark draft pending discussion and playtesting to ensure no bugs.

**Comment by isakube** [comment]
please no

**Comment by EliteMasterEric** [comment]
> please no

Why tho we should use the latest version if there's nothing wrong with doing so, less confusion that way.

**Comment by somefnfplayerlol** [comment]
haxe v4.2.0 or higher hates git for some reason

**Comment by EliteMasterEric** [comment]
@somefnfplayerlol Do you have anything more specific on this issue? Git seems to be just peachy with it, all checks have passed in continuous integration.

**Comment by somefnfplayerlol** [comment]
@ninjamuffin99 says haxe 4.2.0 (or higher?) is broken and is not working with gits properly

**Comment by Nathanisadumbass** [comment]
i build with haxe 4.2.3, no issues, on linux

**Comment by somefnfplayerlol** [comment]
> i build with haxe 4.2.3, no issues, on linux

i guess not

**Comment by itsDARK768** [comment]
Well First The Code May Not Budge Anymore (who knows they could have updated the language in one of the newer updates)

Also It May Also Be A Pain To Port It To The New Haxe Verson So Yea

**Comment by EliteMasterEric** [comment]
Nobody has reported any build issues with 4.2.3 (aside from several deprecations, which are only warnings), even Github Actions likes it. However  someone mentioned the issue is with Git somehow.

**Comment by KlavierGayming** [comment]
i use 4.2.2 (just cuz stuff) and it works perfectly fine with gits?
i think it was specifically 4.2.0

**Comment by somefnfplayerlol** [comment]
`README.md` in ninjamuffin99/Funkin reads:
image

**Comment by EliteMasterEric** [comment]
Again we have no info on what SPECIFICALLY the issue is. Maybe it was fixed in 4.2.3 and it's fine to update, we don't know unless someone can reproduce the problem.

**Comment by RagdollClash** [comment]
I tried 4.2.3 a few days ago and have had no issues compiling FNF, only a lot of warnings from dependencies using depreciated functions

**Comment by TheLeerName** [comment]
btw i now using haxe 4.2.3 anywhere, no errors (i can compile android version (haxe 4.2.2+ needed) and KE without changing haxe version yay)

**Comment by EliteMasterEric** [comment]
I asked the devs of Haxe if they knew anything and they told me they didn't:

HaxeFoundation/haxe#10443

I have come to the conclusion that the issue is probably fixed now, if it ever existed, and this is safe to merge now.

I never decided to try to ping the Funkin dev because he's probably swarmed with pings constantly as it is.

**Comment by EliteMasterEric** [comment]
https://github.com/HaxeFoundation/haxe/issues/10443#issuecomment-948958011

It's official, the issue is fixed now. This can be merged.

**Pull request merged**
