### PR TITLE
Ikkrine/song three

### PR DESCRIPTION
**Pull request by Kirbos**

### CODE REVIEW

**Comment by Spel0** [comment]
30k lines PR into stable, **what could go wrong**

**Comment by arthu-rguo** [comment]
bro i think you accidentally turned your entire mod into a pull request

**Comment by Trayfellow** [comment]
uhhhh i think you werent supposed to do this

**Comment by Trayfellow** [comment]
i think this person accidentally leaked a mod or smthing

**Comment by Raltyro** [comment]
bruh

**Comment by Kirbos** [comment]
Yeah, I know where I mucked up. I had initially downloaded the zipped files to chart but recently was able to understand how to fetch and use the repository. My dumbass then thought “oh, let me import my Zipped mod in so that it can be functional; instead of doing just the .jsons. After that, I realized how royally dumb that was.

**Comment by Kirbos** [comment]
Very sorry about all of that; this is my first mid working with GitHub and I am making a lot of practice out of it; but I am learning as I go and appreciate y’all being able to put up with my inexperience

**Comment by ACardboardBox1** [comment]
close this!!!😭

**Comment by Kirbos** [comment]
Closed

**Comment by Kirbos** [comment]
I'll just take a day or so to watch how to not fuck up again

**Comment by relma2** [comment]
Hi. Name's Relma; Im the one working on the Roseblight FnF mod. I sincerely apologize for the charter making a the whole mod into a PR into the Kade dev repo and wasting all your time.
It is their first time learning git; and they are learning; and as one of the like two people who know how to code on the team it has been hard teaching *everyone* git.
But I promise to make sure everyone on the team is on the same page from here on out :)

**Comment by Spel0** [comment]
> It is their first time learning git; and they are learning; and as one of the like two people who know how to code on the team it has been hard teaching *everyone* git.

I don't think such roles as charter should be collaborators to mod source code in the first place. Like your repo mod is public, so he can download anything he needs to(and if he needs compiled game, then just ask from one of two coders working on the mod), same with charts, just ask one of the collaborators to upload it to repo.
I would see the benefit of for example character artist or background artist(that is if they know how file structure of source code works), but teaching **everyone** how to use git and make them collaborators in my opinion is too much. Imo, only who needs to be collaborator is coders and people who know file structure, everyone else adds files only from asking those 2, this way less littering and unexpected changes nor actions like charter did

**Comment by Kirbos** [comment]
Yeah, what I typically do is get the .ogg's from the musician, figure out what engine I'm using from the coder, and then make the chart in that engine, returning the results in a group message by sharing the .json files. I'm definitely not a code worker, but it was good practice for me to try at least. I now know where my experience lies with these kinds of regards and will most definitely be taking this into future reference. I'm again sorry for that trouble; I never meant to create a problem at this kind of scale.

**Comment by relma2** [comment]
> but teaching everyone how to use git and make them collaborators in my opinion is too much. Imo

Now, I dont think so. I see the value in teaching even the smallest contributor how to actually use git. Pull requests and protecting direct commits to master or stable is how we avoid damage like this. Larger repos manage this by setting what users are or aren't allowed to make pull requests and such.
Not pointing fingers here, but I think the problem is that the forked repo (i.e., Kade Engine) still allows anyone to make a PR. I made Kirbos a collaborator on **my** fork but wasnt aware that that privilege extended up to the other remotes as well.

If only there was a setting between "full collaborator" and "read only" i could set, like "this user is only allowed to edit jsons".

**Pull request closed without merging**
