### PR TITLE
gf fix + ability to disable new system for bf

### PR DESCRIPTION
**Pull request by shaderw0lf**
finally i decided download master branch and test code before doing pull request ahaha

did it because bf shakes his head only in first of four beats and for me its ridiculous

### CODE REVIEW

**Review by Spel0 — COMMENTED** [review]
~~used review incorrectly first time~~ I don't think you should reinvent the wheel tho. It already has the system where you just need to change variable to make bf and dad bop faster. Plus it's kade that adjusted it to be like in the original(even though this sytem works on BPM which is kidna dumb and he tested it on milf only I believe) so

**Comment by Spel0** [comment]
Also I wonder who put tankman there even LOL

**Comment by shaderw0lf** [comment]
dude, i tried to tune that settings and things (maybe only for me) getted worse than was
so i did this pull request because i believe that im not only one who had (and have) problems with that system
(and also i had to fix gf finally by compiling KE and test what i did lmao)

**Comment by Spel0** [comment]
> dude, i tried to tune that settings and things (maybe only for me) getted worse than was

Then just disable it? It's first variable, if you set it to false then it would return to it's original speed.

**Comment by shaderw0lf** [comment]
> Then just disable it? It's first variable, if you set it to false then it would return to it's original speed.

seems im crab and it doesnt work for me)
well, will try to revert things and just finally fix gf

**Comment by Spel0** [comment]
> > Then just disable it? It's first variable, if you set it to false then it would return to it's original speed.
> 
> seems im crab and it doesnt work for me)

Oh yea, I forgot to put condition so it would idle every beatHit. Just add conditions I added in screenshot and set first variable to false, it should work
For dad:
image
For boyfriend:
image

**Comment by shaderw0lf** [comment]
> Oh yea, I forgot to put condition so it would idle every beatHit. Just add conditions I added in screenshot and set first variable to false, it should work
> For dad:
> image
> For boyfriend:
> image

its working! i never wouldnt think about it)
thanks, dude

**Comment by Kade-github** [comment]
so cool? pog

**Pull request merged**
