### PR TITLE
fixed Philly being called Philly Nice in story mode

### PR DESCRIPTION
**Pull request by Lucky-56**

### CODE REVIEW

**Comment by theDetourist** [comment]
No, better to make the song work with the name it was always meant to have.

**Comment by Lucky-56** [comment]
but for some reason they changed it back 21 hours ago [here](https://github.com/KadeDev/Kade-Engine/issues/741#issuecomment-855307570_) on [this commit](https://github.com/KadeDev/Kade-Engine/commit/0d4c7b7978e8ea37802ea3b1999aa564d039f566)

**Comment by theDetourist** [comment]
Shouldn't have, the song was always meant to be named Philly Nice and #480 was working fine.

**Comment by Lucky-56** [comment]
I think so too, but kade and the team had different things in mind I guess so I just fixed what they thought 'was right'

**Comment by Kade-github** [comment]
please redo this on the master branch instead of stable.

**Comment by Kade-github** [comment]
sorry im dumb I forgot I could do it myself

**Pull request merged**
