### PR TITLE
REOPENED: #824 replay fix + modchart fix + stage, gf and noteStyle defaults to their corresponding style if none was found in chart

### LINKED ISSUE #820: Allow different weeks to default to their own stages
If there is no stage value in the .json, allow it to default to the stage typically used for the week. This should fix mods like B-Sides using the Week 1 stage for every week. (Same goes for GF and note skins.)

### LINKED ISSUE #825: Bug Report: more game crashes with spaces in songs
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.2 + #824 
## Please describe your issue. Provide extensive detail and images if possible.
simply I did not fix everything with spaces, when loading a replay with spaces... you guessed it it crashes
\
\
\
\
\
\
_sigh_
\
\
I'll get to fixing it now

### LINKED ISSUE #830: Bug Report: Replay Details doesn't show version
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.2 + #824 
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
go into replay viewer with replays loaded
## Please describe your issue. Provide extensive detail and images if possible.
it does not show the replay version
image

### LINKED ISSUE #862: Bug Report: I can't mod it without the bg always being set as the stage from the tutorial and week 1
I moded b side remixes into kade engine v1.4.2 and wanted to update it to v1.5.2 by putting the assets folder into v1.5.2. It worked but the characters didn't look like they would in b side and the background would always be the tutorial background. I quickly learned that there was a new folder specifically for characters. I still don't know how to get the backgrounds to change to what they should look like. I have tried putting only the songs and data folders from my b side  assets in Kade engine v1.4.2  folder into v1.5.2 but that doesn't work. Please fix this or tell me how to fix it myself because it's really pissing me off.

### PR DESCRIPTION
**Pull request by Lucky-56**
(Adds) Fixes #820
Fixes #862 
Fixes #825
Fixes #830

Fixes [modcharts (mentioned by this)](https://github.com/KadeDev/Kade-Engine/pull/789#commitcomment-52148568)

### CODE REVIEW

**Comment by Lucky-56** [comment]
reason for reopen: I renamed my `master` branch to `patch-1` and it said "I deleted the master branch" :/

**Comment by Jaduplex** [comment]
looks great. sorry that pr was kinda rushed since i was porting it over from a mod branch i had on a much older commit of kade engine cuz conflicts are pain!

**Review by puyoxyz — CHANGES_REQUESTED** [review]
fix modcharts too plz

**Comment by puyoxyz** [comment]
~~oh wait thats the wrong pr i think~~ nvm its the right one

**Comment by Lucky-56** [comment]
yeah was about to do that bc I just saw that too in the comments of my previous pr

**Review by puyoxyz — APPROVED** [review]
testing:
- replay with spaces in song name loads
- replay without spaces in song name loads
- replay details shows the version
- modcharts not tested (i can't, am on linux. someone else test them on songs with spaces in the name before merging!!!!!)
- song with no stage in the json uses the default stage for that week, epic

code looks ok enough

**Pull request merged**
