### PR TITLE
you can compile with 4.0.x

### PR DESCRIPTION
**Pull request by actuallyasmartname**
basically https://github.com/ninjamuffin99/Funkin/pull/726

### CODE REVIEW

**Comment by george2781** [comment]
Well I'm unable to test this like I wanted to because lua stuff is completely broken for me when compiling no matter what I try (yes I have everything needed to compile the game installed, I'm not a moron!) so yea

**Comment by actuallyasmartname** [comment]
> Well I'm unable to test this like I wanted to because lua stuff is completely broken for me when compiling no matter what I try (yes I have everything needed to compile the game installed, I'm not a moron!) so yea

I know this, it only builds on windows for some reason

**Comment by supern64** [comment]
@actuallyasmartname I have gotten it to work on linux, you just need to hold the haxe version on apt to 4.0.5

**Comment by actuallyasmartname** [comment]
accidentally closed myself and didn't notice

**Pull request merged**
