### PR TITLE
use M.I.L.F instead of Milf

### PR DESCRIPTION
**Pull request by RagdollClash**
Just like how `Dadbattle` is now `Dad Battle` and `Philly` is now `Philly Nice`, this PR makes it so that Milf is now M.I.L.F

...idk why i wrote that, this shit self explanatory lol. everything works as expected, as seen below

2021-08-29_12-04-07_Kade_Engine

2021-08-29_12-04-22_Kade_Engine

2021-08-29_12-05-40_Kade_Engine

https://user-images.githubusercontent.com/15317421/131262710-046d0bdc-eaf0-4908-ab1a-1e5e7908132f.mp4

2021-08-29_12-11-40_Kade_Engine

2021-08-29_12-05-03_Kade_Engine

### CODE REVIEW

**Review by Jaduplex — APPROVED** [review]
good

**Review by Lucky-56 — APPROVED** [review]
clean.

Approved

**Comment by RagdollClash** [comment]
:LETSFUCKINGGOOOO:

**Comment by isakube** [comment]
:LETSFUCKINGGOOOO:

**Pull request merged**
