### PR TITLE
Difficulty specific modcharts

### PR DESCRIPTION
**Pull request by ZenusPurity**
Works, might be a little spaghetti but eh at least it works. Simpler than I thought it would be

### CODE REVIEW

**Comment by Aikoyori** [comment]
what about the songs that only has `modchart.lua`

**Comment by NeeEoo** [comment]
The lua modchart already has the difficulty variable. I can't really see a use for this.

**Comment by ZenusPurity** [comment]
> The lua modchart already has the difficulty variable. I can't really see a use for this.

I have realised, didn't know because modchart.md is poofed. I'll close it now.

**Comment by puyoxyz** [comment]
> > The lua modchart already has the difficulty variable. I can't really see a use for this.
> 
> I have realised, didn't know because modchart.md is poofed. I'll close it now.

it's on the website

**Pull request closed without merging**
