### PR TITLE
New debug feature + bug fixes

### PR DESCRIPTION
**Pull request by Spel0**
- ### **New debug feature: ability to press 2 and skip 10 seconds of the song**
Credit for this features code: Shadow Mario#9396 || [Github profile link](https://github.com/ShadowMario)

- Fix of #1301 issue
- Fix of an issue involving BPM not resetting to it's main menu music BPM after completing any week

### CODE REVIEW

**Comment by Spel0** [comment]
Fixed [this monstrosity](https://youtu.be/qXMP7SqE2iE)

**Comment by Kade-github** [comment]
what the fuck happened there

> Fixed [this monstrosity](https://youtu.be/qXMP7SqE2iE)

**Comment by Spel0** [comment]
> what the fuck happened there

Week 6 relies on it's own folder to load arrows, and since results screen resets PlayState story week on song replay, it tries to find it in assets or shared, and then arrows go placeholder logo, and with it crash bomb timer starts ticking.

**Comment by ACardboardBox1** [comment]
> 
> 
> Fixed [this monstrosity](https://youtu.be/qXMP7SqE2iE)

so bad it looks like a damn modchart

**Pull request merged**
