### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by crislikesanimation**
AAAHAHAHA LMAO MY DUMBASS FUCKING EDITED THE KADE FI
LE

### CODE REVIEW

**Review by crislikesanimation — COMMENTED** [review]
kade don't accept this

**Comment by somefnfplayerlol** [comment]
@crislikesanimation close this pr

**Comment by Kade-github** [comment]
ok

**Comment by isakube** [comment]
```diff
+ 1
- 1

+ 
-
```

**Comment by napstaa967** [comment]
dude this was such a great change!
i don't know why it wasn't accepted by kade this was just, one of the best i've seen!

**Pull request closed without merging**
