### PR TITLE
Reset button option

### PR DESCRIPTION
**Pull request by Jaduplex**
brings back R to reset as an option

### CODE REVIEW

**Review by puyoxyz — CHANGES_REQUESTED** [review]
`return "Reset Button " + (!FlxG.save.data.distractions ? "off" : "on");`

should be `return "Reset Button " + (!FlxG.save.data.resetButton ? "off" : "on");`

**Review by puyoxyz — CHANGES_REQUESTED** [review]
`Enable and disable pressing R to gameover.`

should be `Toggle pressing R to gameover.` (see: "`Toggle flashing lights that`...")

could do the same for watermarks if u want since u changed that idk

**Comment by Jaduplex** [comment]
oops!!! i made mistakes!!! ill do these things

**Comment by Jaduplex** [comment]
done!

**Review by puyoxyz — APPROVED** [review]
Yeah

**Pull request merged**
