### PR TITLE
add skip cutscene and skip countdown options

### PR DESCRIPTION
**Pull request by napstaa967**
this is made for issue #1445 
same as #1446 but using master branch and with the countdown option

### CODE REVIEW

**Comment by napstaa967** [comment]
still currently working on a way to make the cutscene option only 1

**Comment by isakube** [comment]
> still currently working on a way to make the cutscene option only 1

imo it's better if it's two separate options. so yeah les go

**Review by isakube — APPROVED** [review]

**Comment by napstaa967** [comment]
drafting because i just found a bug

**Comment by Kade-github** [comment]
don't really like these being options

**Pull request closed without merging**
