### PR TITLE
adding labels n' stuff to the Charting State

### PR DESCRIPTION
**Pull request by isakube**
yeah uh

ok all done

### CODE REVIEW

**Comment by haya3218** [comment]
uh why does this change PlayState?
wh

**Comment by prokube** [comment]
> uh why does this change PlayState?
> wh

good question

that i don't have an answer to
Maybe somebody committed to playstate while i was doing stuff? Which is weird because I never touched PlayState

**Comment by isakube** [comment]
wait

oh fuck
I KNEW THERE WAS SOMETHING WACK ABOUT THE IMPORTS

fixed it with the new commits

**Comment by Kade-github** [comment]
Correct me if i'm wrong, but you don't seem to be modifying ChartingState.hx?

**Comment by isakube** [comment]
> Correct me if i'm wrong, but you don't seem to be modifying ChartingState.hx?

the first commit was me being really tired. I fixed PlayState.hx in e434c9c504a109051f3ced56ae384e25d0f1000a ("lol sorry")

**Comment by Kade-github** [comment]
K I see em now

**Pull request merged**
