### PR TITLE
Repaired HTML5 build CI.

### PR DESCRIPTION
**Pull request by EliteMasterEric**
The issue was with the content of a macro that is disabled on desktop platforms.

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
~~Don't merge this unless all Github's checks succeed.~~

All checks have passed

**Comment by NotSorena** [comment]
this did not fix shit

**Comment by EliteMasterEric** [comment]
> this did not fix shit

https://github.com/KadeDev/Kade-Engine/runs/4056629669?check_suite_focus=true

**Comment by NotSorena** [comment]
i was joking

**Comment by NotSorena** [comment]
only thing is it builds to html5 fine but only loads the haxeflixel loading screen and nothing else

**Pull request merged**
