### PR TITLE
Fix not compiling because of skip step limit and remove useless icons

### PR DESCRIPTION
**Pull request by y579**

### CODE REVIEW

**Comment by Raltyro** [comment]
shouldn't this supposed to be in "issues"?

**Comment by y579** [comment]
idk

**Comment by y579** [comment]
sorry

**Comment by isakube** [comment]
yo bf-old is used for an easter egg if you remove that the game's prob gonna crash when you press `9`
edit: literally don't even know what this pr is lol

**Comment by y579** [comment]
It doesn't crash I checked. it just doesn't change the icon. Oh, and yes, I know about that but I think it's useless

**Comment by isakube** [comment]
> but I think it's useless

Watch this...


## But it's funny

**Comment by ACardboardBox1** [comment]
> 
> 
> > but I think it's useless
> 
> Watch this...
> ## But it's funny

i like the old bf icon it gives much nostalgia 😌

**Comment by Kade-github** [comment]
But it compiles just fine with step limit, if it doesnt just remove it on ur own copy.

**Comment by y579** [comment]
I just feel like it should be gone from the start just for the convenience right?

**Pull request closed without merging**
