### PR TITLE
change how gameplaycustomizestate loads assets

### PR DESCRIPTION
**Pull request by RagdollClash**
this pr makes gameplaycustomizestate use the newly added stage class, reducing hardcoded aspects of the state

a fun addition to this is that we can now change what characters or stages are shown in the state
so, whatever song you choose in freeplay will impact what will be seen in gameplaycustomize state

however the current version of this pr has a few issues such the camera position needing to be adjusted and stage zoom not being respected. if anyone knows how to fix this kinda stuff, please mention it via review
2021-08-23_23-10-04_Kade_Engine
2021-08-23_23-40-43_Kade_Engine
2021-08-23_23-10-37_Kade_Engine
2021-08-24_00-21-28_Kade_Engine

this pr also makes the state use tabs instead of spaces lol, github is not gonna have fun showing the changes

### CODE REVIEW

**Comment by Spel0** [comment]
> however the current version of this pr has a few issues such as gf not being automatically set for some songs, and the camera position needing to be adjusted, hence why it is currently a draft

This can probably be fixed if every stage repositioning code and camera stuff was moved to stage class too, but i've decided not to do it in my previous PR. If you want then feel free to try and put that there too!

**Comment by RagdollClash** [comment]
i was thinking about doing something similar, but i don't think i wanna do that much refactoring (at least with how confident i am with my coding skills atm)

**Comment by RagdollClash** [comment]
think i got the other issues fixed aside from background shenanigans, camera positioning and stage zoom being ignored

**Comment by RagdollClash** [comment]
if someone can figure out how to fix the camera stuff please let me know via review

**Comment by RagdollClash** [comment]
omg git please

i'll recreate the PR later 'cuz that is jank

**Pull request closed without merging**
