### PR TITLE
Make gf's week 6 animations look smoother

### PR DESCRIPTION
**Pull request by ACardboardBox1**
I always thought her animations looked weird so i made them smoother

### CODE REVIEW

**Comment by ACardboardBox1** [comment]
gonna do this with the bg girls too 

edit: nvm they look ugly lol

**Comment by ACardboardBox1** [comment]
oops hold on i think i need to do a little bit of fixing still

edit: nvm
edit 2: well actually yes there still is a problem i'll have to fix it lol

**Comment by isakube** [comment]
i have no idea what is happening here

**Comment by ACardboardBox1** [comment]
> 
> 
> i have no idea what is happening here

me doing a lot of commits just to undo most of them 

it just replaces the gf's animations with smoother ones

**Comment by theDetourist** [comment]
Video of it in action or no deal.

**Comment by ACardboardBox1** [comment]
> 
> 
> Video of it in action or no deal.

oh yeah ok ok i'll try recording it or right as when i get the chance since its late asf

**Comment by ACardboardBox1** [comment]
Fuck there's still a problem

this is a unnecessarily long pr

**Comment by roythearsonist** [comment]
Wouldn't this be a pull request for the main repo though?

**Comment by theDetourist** [comment]
> 
> 
> Wouldn't this be a pull request for the main repo though?

Master is the branch for unstable development, stable is the branch you download if you want to mod.

**Comment by roythearsonist** [comment]
I meant for the actual Funkin repo

**Comment by ACardboardBox1** [comment]
I was planning to do it with the normal funkin branch too.

**Comment by roythearsonist** [comment]
Oh, so you're doing this to make sure kade wont forget to merge it, thinking it had nothing to do with KE

**Comment by ACardboardBox1** [comment]
yk nvm with this i'll just leave it as is for now

**Pull request closed without merging**
