### PR TITLE
fix the god damn campaign arrows

### PR DESCRIPTION
**Pull request by isakube**
asdhlfhjasdkflhjdaskfhdalsjkfha;dslfkadjfsgklhdagliugad;'g;dsofja;glgs;g;asfgasfglu

### CODE REVIEW

**Comment by ACardboardBox1** [comment]
> 
> 
> asdhlfhjasdkflhjdaskfhdalsjkfha;dslfkadjfsgklhdagliugad;'g;dsofja;glgs;g;asfgasfglu

are you okay

**Comment by isakube** [comment]
> > asdhlfhjasdkflhjdaskfhdalsjkfha;dslfkadjfsgklhdagliugad;'g;dsofja;glgs;g;asfgasfglu
> 
> are you okay

no this has been plaguing fnf since 0.2.4 i think

**Comment by Futuremappermydud** [comment]
what changed here

**Comment by isakube** [comment]
> what changed here

arrow colors lol

**Pull request merged**
