### PR TITLE
Remove 'beat' from the chart file.

### PR DESCRIPTION
**Pull request by EliteMasterEric**
Clean up the beat logic such that it no longer clutters up the chart note data.

### CODE REVIEW

**Review by somefnfplayerlol — APPROVED** [review]

**Comment by Kade-github** [comment]
but beat is used, and its actually really useful for sm conversion.

and actually the entire editor works around beats.

**Comment by isakube** [comment]
BREAKING NEWS: MasterEric PR CLOSED!! (Third ever) (ACTUALLY HAPPENED)

**Comment by EliteMasterEric** [comment]
Literally don't understand why this is closed, my understanding of the code indicates that notes are based on strum time (in seconds since song start).

**Comment by Kade-github** [comment]
Maybe read the message i closed it on lol

**Comment by EliteMasterEric** [comment]
Isn't beat just derived from the strumtime? See my PR, it makes it redundant.

**Comment by Kade-github** [comment]
Strumtime is derived from the beat actually (in editor) Song conversion takes it from the time due to other charting formats not giving a beat. And it only does it if its not a ke chart already. The editor is fully based on beats due to snap and just how beats are better. This also helps the charter in adding bpm changes and making it align notes to the right bpm

**Pull request closed without merging**
