### PR TITLE
Adding practice mode

### PR DESCRIPTION
**Pull request by epicbobmanbob**
This adds a feature called "Practice Mode" which means you cant die but you cant save any scores.

### CODE REVIEW

**Review by Lucky-56 — APPROVED** [review]
just looked over this barely but looks good

**Comment by isakube** [comment]
yiy

**Comment by ACardboardBox1** [comment]
#1144 or something lol

**Comment by Kade-github** [comment]
First id rather remake options then adding this, additionally, i dont like thid approach making it an option id rather have a CH kind of way

**Pull request closed without merging**
