### PR TITLE
two things that literally don't affect anything

### PR DESCRIPTION
**Pull request by isakube**
First one fixes not having a selection in the main menu.

Second one just creates a fancy url opener that accounts for Linux.

This probably won't get merged but hey

### CODE REVIEW

**Comment by ghost** [comment]
URL Opening for Linux? I'm in! (Ubuntu user here)

**Comment by isakube** [comment]
> URL Opening for Linux? I'm in! (Ubuntu user here)

yeah the outdated substate just used flxG.openURL so i fixed it

**Comment by puyoxyz** [comment]
> URL Opening for Linux? I'm in! (Ubuntu user here)

ew canonical distro

**Comment by ghost** [comment]
I just got it a while ago and don't want to switch out because it wouldn't be very convenient.
On my very old laptop I have Arch

> > URL Opening for Linux? I'm in! (Ubuntu user here)
> 
> ew canonical distro

**Comment by isakube** [comment]
> On my very old laptop I have Arch

Arch user

**Comment by ghost** [comment]
yeah
I needed Arch though. Anything else is too laggy to use.

**Comment by puyoxyz** [comment]
arch :3

**Pull request merged**
