### PR TITLE
Custom noteskin support

### PR DESCRIPTION
**Pull request by ItzFireable**
- Option in settings to change noteskins.
- Added another default skin, circles by Foxeru (fox# 0669) (Unfinished, missing hit glow).
- Updated every noteskin system to use the currently selected noteskin.

Going to add a few new default skins with Foxeur later on, and a feature to override skins set by chart (currently never overrides).

### CODE REVIEW

**Comment by Kade-github** [comment]
Ill fix dis later

**Comment by Burger-Gaming** [comment]
pixel circle notes sir where are they

**Comment by ItzFireable** [comment]
> pixel circle notes sir where are they

they don't exist, got nobody who can make them. that's why atm its not overriding pixel skins.

**Comment by olivier6513893** [comment]
> > pixel circle notes sir where are they
> 
> they don't exist, got nobody who can make them. that's why atm its not overriding pixel skins.

This exists https://gamebanana.com/mods/30861

**Comment by ItzFireable** [comment]
> > > pixel circle notes sir where are they
> > 
> > 
> > they don't exist, got nobody who can make them. that's why atm its not overriding pixel skins.
> 
> This exists https://gamebanana.com/mods/30861

we made our own assets. we're not taking others assets unless they contribute themselves or we get their permission.

**Pull request merged**
