### PR TITLE
Ability to change deafult HUD font

### PR DESCRIPTION
**Pull request by libauror-a**
In other words, the HUD text (Score text, watermark, etc) uses the developer selected font.

This dosen't do anything for the game, just a asthetic change.

Example, week 6 using the pixel font:
image

### CODE REVIEW

**Comment by Jaduplex** [comment]
YO i love this

**Review by george2781 — APPROVED** [review]
Looks good to me

**Comment by itsvyrus** [comment]
Swaggy

**Comment by libauror-a** [comment]
I whoud add some font size changes to the pixel font but now i'm to nervous to change the code because i think i will mess something up.

**Comment by puyoxyz** [comment]
text needs to move up it gets cut off

**Review by theDetourist — APPROVED** [review]
Fine addition, whoever, it messes up some small things in the game but nothing too horrific that may lead to the PR being denied completely.

broken_1

broken_2

If you think you can fix these, go for it. We'll help you if you need assistance.

**Comment by puyoxyz** [comment]
> Fine addition, whoever, it messes up some small things in the game but nothing too horrific that may lead to the PR being denied completely.
> 
> broken_1
> 
> broken_2
> 
> If you think you can fix these, go for it. We'll help you if you need assistance.

About the top picture, I agree, but the song progress bar text has always been off center

**Comment by theDetourist** [comment]
> About the top picture, I agree, but the song progress bar text has always been off center

Yeah I know, was just talking about it bleeding out of the song progress bar.

**Comment by puyoxyz** [comment]
Anyways, I don't really think this PR is a good idea anyways since the current font already fits with the pixel aesthetic.

**Comment by libauror-a** [comment]
Right now i'm trying to fix the aligment.

**Comment by libauror-a** [comment]
Done, all i just need to do is fix the song position bugs.

**Review by oketariq — APPROVED** [review]
looks cool

**Comment by theDetourist** [comment]
I take back my endorsement. Why are you trying to sneak in #292 inside this PR again?

wtf

wtf_2

wtf_3

**Comment by Kade-github** [comment]
lmaooo. thats funny. Please remove all code references from Project FNF. thanks

**Comment by aflacc** [comment]
how dare

**Pull request closed without merging**
