### PR TITLE
Add "Player 2 Change" event and remove SM/make SM not obligatory

### PR DESCRIPTION
**Pull request by ghost**
It might be the best change in Kade Engine lol.

Also SM is fucking complicated.

### CODE REVIEW

**Comment by isakube** [comment]
you're merging stable to master lol, try again

**Comment by somefnfplayerlol** [comment]
why are you merging stable to master, this doesn't make any sense

**Comment by EliteMasterEric** [comment]
They probably made a fork and then didn't set it as the source branch for the change properly.

**Comment by Spel0** [comment]
Clickbait title, nothing of the things said in there was actually added nor removed, blamming this guy

**Comment by EliteMasterEric** [comment]
> Clickbait title, nothing of the things said in there was actually added nor removed, blamming this guy

As I said, what I'm imagining happened is:

* LevitoDev creates a change on their local clone.
* They commit the change but forgets to push it to their GitHub.
* They then assume everything is fine and tries to make a PR but uses the wrong branch because they don't have any code pushed.

This weird PR is the result. LevitoDev probably needs to fix something on their end.

**Comment by Spel0** [comment]
Still getting blammed

**Comment by RagdollClash** [comment]
even on their repo, there's nothing related to this PR at all

**Comment by ghost** [comment]
sorry my brain is small lol

**Pull request closed without merging**
