### PR TITLE
fix the names of mom right pose

### PR DESCRIPTION
**Pull request by napstaa967**
for some reason it said left pose and no one fixed it

### CODE REVIEW

**Comment by isakube** [comment]
well i mean it still functions but

sure

**Comment by RagdollClash** [comment]
fyi: this is gonna cause issues with character mods that go over mom

**Comment by napstaa967** [comment]
> fyi: this is gonna cause issues with character mods that go over mom

oh yeah i just realized

**Comment by Kade-github** [comment]
COMPATABLITY GONE

**Pull request closed without merging**
