### PR TITLE
Workldof recolored assets

### PR DESCRIPTION
**Pull request by izzonac**
[stage, and NODE_assets recolored.zip](https://github.com/KadeDev/Kade-Engine/files/6666833/stage.and.NODE_assets.recolored.zip)

### CODE REVIEW

**Comment by Lucky-56** [comment]
what is this pr?

**Comment by Lucky-56** [comment]
please close this if it was unintentionally, if not it'll get closed anyway

**Comment by isakube** [comment]
what in the

**Comment by puyoxyz** [comment]
imma assume this pr was an accident

**Pull request closed without merging**
