### PR TITLE
Character Colored HP Bars Option now visible and Colors Have Been Improved!

### PR DESCRIPTION
**Pull request by raf13lol**
The Title Says It All.

### CODE REVIEW

**Review by ACardboardBox1 — COMMENTED** [review]
the option being visible is okay but the color improvement looks like it makes it harder ngl.
besides, looks good.

**Comment by Kade-github** [comment]
resolve conflicts

**Comment by raf13lol** [comment]
image
first there is no conflicts 2. this extra code from old one doesnt exist finally
image
THE WINDOWS DEV BUILD WORKED??????????????????? how does github think that this code is bad

**Comment by cah-keith-baker01** [comment]
You need to merge in Kade-Dev:master into your branch. In the github UI it says:
> Conflicting files
> source/PlayState.hx

**Comment by raf13lol** [comment]
i will open a new pr because there is too many commits

**Pull request closed without merging**
